Exceptions handled in Data Engineering
kkkarthik6/nlpipe pull request #4
Opened 2020-08-11 15:14 UTC by kkkarthik6

Introduced exception handling.

2020-08-12 15:54 UTC, disssid requested changes

2020-08-12 15:54 UTC, disssid commented on src/nlpipe/pipelines/data_engineering/nodes.py
> +            warnings.warn("No target column provided, All data points will have same target value, Please use target argument to provide target labels", NoTargetWarning)
Will a warning suffice or an error needs to be raised?

2020-08-12 15:54 UTC, disssid commented on src/nlpipe/pipelines/data_engineering/nodes.py
> +            test_y=test_y,
Unnecessary , at the end

2020-08-12 15:54 UTC, disssid commented on src/nlpipe/pipelines/data_engineering/nodes.py
> +
Add valid comments where ever possible to better understand the logic

2020-08-15 19:54 UTC, kkkarthik6 commented on src/nlpipe/pipelines/data_engineering/nodes.py
> +        if len(self.target) < 1:
Done

2020-08-15 19:54 UTC, kkkarthik6 commented on src/nlpipe/pipelines/data_engineering/nodes.py
> +        if len(self.columns) < 1:
Sure

2020-08-15 19:55 UTC, kkkarthik6 commented on src/nlpipe/pipelines/data_engineering/nodes.py
> +            warnings.warn("No target column provided, All data points will have same target value, Please use target argument to provide target labels", NoTargetWarning)
For unsupervised scenarios, we do not need labels, Hence I think warning would suffice.

2020-08-15 19:57 UTC, kkkarthik6 commented on src/nlpipe/pipelines/data_engineering/nodes.py
> +            test_y=test_y,
Trying to return dictionary, Hence key value pairs. It doesn't have to be a dictionary though, What would you suggest? return dictionary or tuple

2020-08-18 13:31 UTC, disssid commented on src/nlpipe/pipelines/data_engineering/nodes.py
> +            test_y=test_y,
a dictionary sounds good

2020-08-19 12:41 UTC, merged